### ISSUE TITLE
+44 bug

### ISSUE THREAD

**Issue by flyrev** [Bluefieldscom/intl-tel-input#106]
When I enter +44, it only accepts my next two digits.

**Comment by jackocnr** [comment]
@flyrev as promised, I have created a separate `preventInvalidNumbers` option, which defaults to false.

@ispyropoulos if you enable the new `preventInvalidNumbers` option, I now trigger `invalidkey` if we ignore a key because it would lead to an invalid number.

Both features are in v3.8.4. Thanks for your input.

**Comment by ispyropoulos** [comment]
@jackocnr that's great news! I'll check the new option out soon. I have to release an updated gem as well, as it is 2-3 months behind by now.
