### ISSUE TITLE
Dropdown list not working in Iphone and Android devices.

### ISSUE THREAD

**Issue by Cloudchoice** [Bluefieldscom/intl-tel-input#118]
Hi,

In Android and Iphone devices, the dropdown list does not display the navigation arrows. This makes it impossible to choose other countries.

Is there any solution?

**Comment by bs-thomas** [comment]
@jackocnr Hello there, would like to just mention that this issue seems to be still existing.  For my situation it's using a pop-up package called magnific pop-up.  I'm not sure if it happens without that, but for sure, using fullstory.com's live UX replay feature, I can see a number of users experiencing this problem.  I admit not all iOS is having this issue, because mine was fine.

**Comment by jackocnr** [comment]
I'm guessing this is an issue with older devices. Previously Android 4.2.1 was mentioned, and that came out 5 years ago. I just tested with BrowserStack, and it worked fine on devices running iOS 10, 9, 8, 7 and 6.

I'm going to leave this issue closed unless someone can provide a specific phone make/model/os version that we can reproduce the problem with, using the vanilla plugin e.g. on http://intl-tel-input.com

**Comment by bs-thomas** [comment]
@jackocnr Thanks for your message.  Sorry it seems like it wasn't the plugin problem.  Though I'd like to share the problem here.  I was using Magnific Popup together with intl-tel-input, and Magnific Popup had a problem causing the background in the scene to scroll in iOS while the popup is active.  So I followed the instructions in this issue:

https://github.com/dimsemenov/Magnific-Popup/issues/12

In the fix, it suggested to do a preventdefault on "touchmove" event inside body.  This was causing the scrolling the fail.

Removing the preventdefault fixed my problem.

Hope this would help people who come across this thread.
