### ISSUE TITLE
Add missing country - Kosovo

### ISSUE THREAD

**Issue by girtsl** [Bluefieldscom/intl-tel-input#150]
I have only gone through the list of European countries, other might be missing as well.

Kosovo http://en.wikipedia.org/wiki/Kosovo

Kosovo declared its independence in 2008. It is recognised by 108 UN members and Taiwan. http://en.wikipedia.org/wiki/List_of_states_with_limited_recognition

**Comment by jackocnr** [comment]
Interesting! According to [Telephone numbers in Kosovo](http://en.wikipedia.org/wiki/Telephone_numbers_in_Kosovo) it's dial code (+383) only came into effect on January 1, 2015.

There are 2 problems though: firstly it doesn't yet have it's own [ISO 3166-1 alpha-2](http://en.wikipedia.org/wiki/ISO_3166-1_alpha-2) country code, though it has been given a temporary one of `xk` by some countries/organisations. Secondly, the [flags service](http://www.flag-sprites.com/) I use to get the flags doesn't yet have one for Kosovo! I will ask them to add one.

**Comment by girtsl** [comment]
I guess it's fair to use the code `XK` until they get a permanent one. Let's hope the guys at flag-sprites also recognise Kosovo.

**Comment by jackocnr** [comment]
I just got this response from the flags guy: "Thank you for your interest in my project. Unfortunately I don’t have much time for it now, but will try to update it as soon as possible!".

So I guess we will just have to wait. There is also this issue about changing to another set of flags, but I don't have time to implement that right now: https://github.com/Bluefieldscom/intl-tel-input/issues/65

**Comment by girtsl** [comment]
Yeah, I guess everyone is busy with something. :)

**Comment by jackocnr** [comment]
A little update on this situation. We've now switched to a different set of flag icons in order to support retina devices. The new flags are from a github project (link at bottom of readme), but I don't think they have support for Kosovo yet either (or at least they don't have a flag for the XK country code). Please feel free to raise an issue with them, but for now I'm going to close this issue. When they add support for Kosovo, please feel free to re-open this issue! Cheers.

**Comment by girtsl** [comment]
https://github.com/lipis/flag-icon-css/issues/43

**Comment by ziggamon** [comment]
Even if we don't have a flag it would be useful to be able to select the country code for Kosovo in the country picker.

**Comment by jackocnr** [comment]
Do you mean +383?

**Comment by ziggamon** [comment]
Yes!

On Jun 11 2016, at 11:37 pm, jackocnr &lt;notifications@github.com&gt; wrote:  

> Do you mean +383?

>

> —  
You are receiving this because you commented.  
Reply to this email directly, [view it on GitHub](https://github.com/jackocnr
/intl-tel-input/issues/150#issuecomment-225395873), or [mute the
thread](https://github.com/notifications/unsubscribe
/AAFohDjR_t0U0IFw2EsLyPmrLpk-MPQ_ks5qKyqJgaJpZM4Da23X).![](https://github.com/
notifications/beacon/AAFohF1GLwgTAfwC8FFT4RlKtoD3CrV9ks5qKyqJgaJpZM4Da23X.gif)

**Comment by jackocnr** [comment]
Added in v9.0.0.

**Comment by ziggamon** [comment]
Awesome!

  

Btw, what's the best place to read release notes for the new releases?

On Jun 12 2016, at 12:03 am, jackocnr &lt;notifications@github.com&gt; wrote:  

> Added in v9.0.0.

>

> —  
You are receiving this because you commented.  
Reply to this email directly, [view it on GitHub](https://github.com/jackocnr
/intl-tel-input/issues/150#issuecomment-225396963), or [mute the
thread](https://github.com/notifications/unsubscribe/AAFohExtR-Cmr-
oDzBmHMBJlvVM-40paks5qKzCzgaJpZM4Da23X).![](https://github.com/notifications/b
eacon/AAFohAfi3IYinwm_T5ADLujmwnendfy0ks5qKzCzgaJpZM4Da23X.gif)

**Comment by jackocnr** [comment]
https://github.com/jackocnr/intl-tel-input/releases
