### ISSUE TITLE
No dial code in input

### ISSUE THREAD

**Issue by shumlvi** [Bluefieldscom/intl-tel-input#169]
There's no dial code in input at all (focus or no focus) in last version. But version 3.5.2 works fine though.

**Comment by jackocnr** [comment]
That's because `nationalMode` now defaults to true. I made this change because I think it's a better experience for users. Check the readme for more info, but let me know if you have any questions. Definitely let me know if you decide to set `nationalMode` back to false as I'd really like to hear about your use case.

**Comment by shumlvi** [comment]
Oh, thank you, I thought that autoHideDialCode is responsible for that. Now I see the difference. 
We need to send the whole number with dial code to api, and it is easier to take it from input at once (without using utils). Plus, when using MVC framework it is easier to observe input value.
