### ISSUE TITLE
Hi Res flags image not loading

### ISSUE THREAD

**Issue by mohammedkhan** [Bluefieldscom/intl-tel-input#183]
Hi, I downloaded the package today for my site and found the flags image wasn't loading, Chrome was giving a 404 error for the hi-res flags image file. I found removing the '@' symbol from the filename and updating the css accordingly fixed the problem. I don't know if this is specific for my local instance, I would have opened a pull request to push through this change but I just wanted to put it on here in case it may be something else.

**Comment by jackocnr** [comment]
Hi Mohammed, this information was in the Troubleshooting section of the readme, but I've now moved it up to the [Getting Started](https://github.com/Bluefieldscom/intl-tel-input#getting-started) section because I think it makes more sense there. Let me know if you have any more questions around this.
