### ISSUE TITLE
Flag options

### ISSUE THREAD

**Issue by pentool** [Bluefieldscom/intl-tel-input#189]
Hi, great script! Thanks!
Just a wish list: would be nice to have an option to disable the flags and drop down.

**Comment by jackocnr** [comment]
Have you tried disabling the input?

**Comment by pentool** [comment]
I got rid of the drop down but didn't dig into the flag part. Just thought a simple option would be easier. This way I don't have to modify the original script.

**Comment by ceejayoz** [comment]
@pentool No need to modify the script, just override two things in your site's CSS.

    .intl-tel-input .flag-dropdown { display: none; }
    .intl-tel-input input[type=tel], .intl-tel-input input[type=text] { padding-left: 12px; }

**Comment by jackocnr** [comment]
I need to clarify something. @pentool when you say **disable** do you mean show them but prevent them from being clicked, or do you mean you want to completely hide them?

**Comment by pentool** [comment]
I meant completely hide them.
I really like the functionality, but we have a narrow box where ppl enter phone numbers. The extra flags gives us little room.

But style override helped. Thank guys!

**Comment by jackocnr** [comment]
Let's just use the style override for now. If more people ask for this feature, maybe I will consider building an option to support this.

**Comment by lulalalalistia** [comment]
I was faced with the requirement that the for the selected option, instead of showing the flag we show the country code. Would be nice to open a few view generation methods to allow us to override :)

**Comment by jackocnr** [comment]
IMO it's misleading to display the  country code next to the national number because the two things together do not necessarily make a valid number (e.g. in the UK national numbers have an extra '0' prefix that is not present in the international numbers).

Can I ask why you want to display the country code? Have you considered setting nationalMode to false?

**Comment by lulalalalistia** [comment]
Its just a requirement from the spec :P
But giving the developer freedom to fine-tune the DOM is never a bad thing right?
Currently my JS-fu is not strong enough. Is it possible to monkey-patch the `_generateMarkup` method from outside?

**Comment by jackocnr** [comment]
I'm afraid that's not possible. And "it's just a requirement from the spec" is not a good reason!

Yes I'm all for empowering devs, but I'm really cautious about adding unnecessary complexity/weight to the plugin. But if a few people ask for something, and they give a good reason, then I'm very open to adding it.

**Comment by lulalalalistia** [comment]
I was thinking the functionality to just allow users to monkey-patch/override the `_generateMarkup` would be less work/more flexible than to have a flag option.

But the reason of the spec would be, the flag is too small and can be easily ignored. We prefer to have country name and calling code clearly stated on the outside. We also would like to color some countries differently, to give visual ques that these countries will be handled differently (e.g. do not support sms verification).

**Comment by jackocnr** [comment]
It would be dangerous to open up private methods (like `_generateMarkup`) to allow people to override them because then everything would break if we decided to change the way that method worked, or what it's responsibilities were, or to rename it etc.

I've already stated why it doesn't make sense to display the country calling code outside of the number, but if you want to discuss this matter further can you please open a separate issue for it.
