### ISSUE TITLE
Country code select tab navigation

### ISSUE THREAD

**Issue by brunops** [Bluefieldscom/intl-tel-input#195]
First of all, thanks for this amazing plugin. 
Sorry if this is a duplicate, but couldn't find this topic in the README or the closed issues. I'm currently having one problem when tab navigating the form, which is the flags dropdown not getting focus (probably because it is a `ul` element, and not a form field), is there any way around it?

Thanks

**Comment by jackocnr** [comment]
Yes I agree: ideally you would be able to tab to the dropdown, but yes you're right: it would only work if the dropdown was a normal `<select>` element, which we can't do, as we'd lose all the nice styling. I know some browsers support custom styling of `<select>` elements, but I know it's difficult (different in each browser), and limited (not sure if we could have flags in the dropdown, not sure if we could style the selected flag in the input to look right, and I know you can't do it at all in older versions of IE). Needs more research.

**Comment by kirkas** [comment]
I suggest adding the `tabindex` attribute on the `.selected-flag`, ditch the `click`event and use the `focus` & `blur` events and accordingly show/hide the country-list.

I manage to make this work with a quick hacky play around on the demo page:

![screen shot 2015-04-01 at 11 09 59 am](https://cloud.githubusercontent.com/assets/1159783/6948022/e700f4e6-d85f-11e4-92ed-1408cf47c922.png)

I think this should be the default plugin behavior as this is a huge improvement for accessibility (tab & click VS click only).


Ref for making an element tabbable:
http://stackoverflow.com/questions/13637223/how-do-you-make-a-div-tabbable

**Comment by kirkas** [comment]
Here's what it look like if you put `tabindex` and `focus/blur` event on the `.flag-dropdown` instead of the `.selected-flag`

![screen shot 2015-04-01 at 11 25 07 am](https://cloud.githubusercontent.com/assets/1159783/6948299/c8ea8bb4-d861-11e4-9d4b-888679695956.png)

Theoretically, you could even tab trough the list of country, or just the preferred country as tabbing trough 235 element might be quite painful for the user.

**Comment by brunops** [comment]
Hey, thanks for the quick replies.

@jackocnr 
Agreed, using a `<select>` element is probably not an option.

@kirkas 
You're right! This might be the way around this, I personally would expect it to behave just like a `<select>` element, so `tabindex` would only be in `.selected-flag` or `.flag-dropdown`, I'll try to play around with it.

Thanks.

**Comment by jackocnr** [comment]
We also need to decide how you open the dropdown once it's focused. I think it should behave as close to a native `<select>` as possible. So I don't want it to open on focus, but I think `up`/`down` would be good, as the browsers I tested would either open a `<select>` dropdown, or rotate through it's options on these keys, and as I don't want to implement the latter, I think we should go with the former. Also some browsers open a `<select>` on `space` too, so I would be up for that as well. Then once the dropdown is open, they can navigate with `up`/`down` or by typing a country name.

Thoughts?

**Comment by kirkas** [comment]
Going as close to select make sense, although the logic should not be to imitate select, but rather to think what's the best user experience for this particular action (selecting a country), which in this case, is imitate select behavior (lolz).

A quick study of different plugin and play around with a native select item show that the common pattern are:

- Element is focusable.
- Dropdown open on `up` and `down`.
- When dropdown is open, `up` and `down` goes trough the options.
- `space` key open the dropdown.
- When dropdown is open, `space` key close the dropdown and select currently focused item.
- When dropdown is open, `enter` key close the dropdown and select currently focused item.
- `enter` key has otherwise no effect, as it might submit the form by mistake (that should probably be prevented by the plugin, since you're not actually using a `select` element).
- When dropdown is open, `tab` key has no effect.

Some of those behavior might be to frigid for your plugin, eg: When the dropdown is open and you hit tab, you might want to close and go to the next input?

Overall I think it should first get as close from a select element, then it'll need a lot of testing to see what's the more convenient and comfortable user experience.

Few ref:
http://github.hubspot.com/select/docs/welcome/
http://harvesthq.github.io/chosen/
https://select2.github.io/examples.html
http://jqueryui.com/selectmenu/
http://brianreavis.github.io/selectize.js/

**Comment by kirkas** [comment]
Also I like the way google signup handle it: https://accounts.google.com/signup

**Comment by jackocnr** [comment]
Yer Google open the dropdown on enter, which I think makes sense because no one is going to be trying to submit the form when the flag is selected.
