### ISSUE TITLE
Required attribute on input

### ISSUE THREAD

**Issue by bkramsay** [Bluefieldscom/intl-tel-input#211]
Hello, thank you for the plugin it's great. 

If I add the "required" attribute to the input field, the default browser error alert doesn't appear.
Is there anyway I can get this to work. 

If not, how can I get an error message to appear rather than just focus on the telephone field.

Thank you very much.

**Comment by jackocnr** [comment]
I just tested it [here](http://codepen.io/jackocnr/pen/yehvE) and it seems to work: just focus the input and hit enter to submit the form.

**Comment by bkramsay** [comment]
Thank you for the response, I forgot to mention the variables I have set as I need the country code to show in the input. I have extended your example here

http://codepen.io/anon/pen/yNBmNq

Variables set

$(".tel").intlTelInput({
  //autoFormat: false,
  autoHideDialCode: true,
  autoPlaceholder: true,
  defaultCountry: "auto",
  nationalMode: false,
  //onlyCountries: ['us', 'ch', 'ca', 'do'],
  preferredCountries: ['cn', 'jp'],
  //responsiveDropdown: true
});

**Comment by jackocnr** [comment]
So the problem is related to the `autoHideDialCode` option. If you enable this, then focusing an empty input will automatically insert the dial code, and blurring the input again will remove it. There's no way to have the browser's `required` check work properly when using this option. You could either do the check yourself, or disable this option. Though I personally recommend using `nationalMode` so your users don't have to deal with country dial codes at all.

**Comment by bkramsay** [comment]
Ok, Thank you for your help
