### ISSUE TITLE
Pluggable ipinfo lookup

### ISSUE THREAD

**Issue by mrchief** [Bluefieldscom/intl-tel-input#225]
By default, the lookup is made against ipinfo.io. It'd be great if this URL or lookup can be made pluggable with an in-house solution (Currently, due to security policies, the client I need this for doesn't allow a direct lookup against ipinfo.io. They have their own homegrown solution which needs to be leveraged instead).

So instead of relying on a specific service, one would rely on a specific data contract. As long as the service returns certain fields in the response, the plugin doesn't care where it came from. 

Looking at the source, it appears that all you need is the 2 digit country code, so it seems pretty doable, unless I'm overlooking anything.

Thoughts?

**Comment by jackocnr** [comment]
There are a couple of pending pull requests around this stuff (2 solutions to the same problem I think) - would they solve your problem?

Otherwise you could just get the country code yourself first, by whatever method, and only then go on to initialise the plugin, setting `defaultCountry` to that country code?

**Comment by mrchief** [comment]
Yeah. I too would second the idea of having a pluggable provider, rather going with a list of supported providers. We have automated bower restore so I'd like something that is available mainstream. Until you merge this, I think doing the lookup myself and defaulting the country is a good idea as well.

**Comment by jackocnr** [comment]
Great
