### ISSUE TITLE
Custom placeholder phone number

### ISSUE THREAD

**Issue by caseyjhol** [Bluefieldscom/intl-tel-input#229]
I noticed a few of the placeholder phone numbers are too similar to actual phone numbers. For example, for UK phone numbers, the placeholder is 07400 123456. This was confusing to a few users, as at first glance it can appear to be an actual phone number. I added a `placeholderNumber` option and set the placeholder number to be `000000000000` (extra digits to accommodate for other countries), and then the placeholder number is set to 00000 000000.

It's a simple implementation (3 or 4 lines of code). Is this something you'd interested in adding? If so, I can do a pull request.

**Comment by jackocnr** [comment]
Hmm I see your point that the example number does look like it could be a real number, but then I don't think just having zeros is a good solution either because it's nothing like a telephone number - I personally would find that confusing.

To be honest, I think the problem here is one of styling - in modern browsers you can use CSS to style the placeholder text - you could just make it a very light grey to make it super clear that it is just a placeholder?

I'm open to other ideas, but all zeros doesn't feel right to me. The placeholder also depends on the `numberType` option, so if this is set to be a landline, then the placeholder will be an 01 number, and if you set it to mobile (the default I believe) then it will start 07. Having the placeholder number be of the right type helps the user understand what is wanted of them, and replacing any number with all zeros loses this information.

**Comment by caseyjhol** [comment]
Perhaps all zeros isn't the way to go, but I still think it wouldn't be a bad idea to have the option to set the number - maybe a few different options depending on numberType and/or the option to have a "global" placeholder number with the ability to override it depending on country. The placeholder number does look a bit confusing for UK with all zeros, but with US numbers, `(000) 000-0000` gets the point across (it's a phone number) without being confused with an actual number. I'm not exactly sure what the best implementation is here, but I think at the very least having the ability to set the placeholder phone number is pretty important and can be accomplished pretty easily.

**Comment by jackocnr** [comment]
You can set a global placeholder yourself just by using the `placeholder` attribute on your `<input>`. If you think the numbers generated by libphonenumber are confusing, maybe you could speak to them about it. Honestly it's beyond the scope of this plugin to try and implement a system of allowing a custom placeholder for each of the 200+ countries - it's unrealistic and unmaintainable.

**Comment by caseyjhol** [comment]
Using `placeholder` overrides the phone number formatting for each country, defeating the purpose of even having the placeholder.

**Comment by jackocnr** [comment]
Yes that's why I called it a global placeholder. For me it doesn't defeat the purpose of having a placeholder because for me a placeholder is a way to explain to the user what they are supposed to do, and if the placeholder you choose matches the initial country, then I think it makes sense. Once they decide to change the country, you can assume they have already understood what they are supposed to do, so the placeholder has done it's job.

Obviously this wouldn't work with `defaultCountry=auto` because you wouldn't know what the initial country would be.

**Comment by jackocnr** [comment]
Either way I appreciate the feature request, but I think it's too much at this time.

**Comment by caseyjhol** [comment]
I'll want a global way to set the placeholder when I initialize the plugin, as it's inconvenient to have to set the placeholder attribute for every field. Fortunately it's only 2 extra lines of code to implement a global placeholder option, so it'll be easy to just modify future versions myself. Thanks!

**Comment by jackocnr** [comment]
^ just re-reading this, you know you don't have to modify the plugin to achieve this, right? you can just set the `autoPlaceholder` option to `false` (so the plugin wont do anything to the placeholder) and then you're free to update the placeholder attribute on your `<input>` element whenever you want...

**Comment by jackocnr** [comment]
Also I just realised a way you can have a custom placeholder per country: just listen for the `change` event (fired when the selected flag changes), and then use `getSelectedCountryData` to know which country is currently selected, and then update the placeholder attribute on the `<input>` to whatever you want!
