### ISSUE TITLE
Public method for open select

### ISSUE THREAD

**Issue by nicksyndicate** [Bluefieldscom/intl-tel-input#234]
Hi. Thanks for plugin!

How to open dropdown without clicking on flag?

I tried ```$('.selected-flag').click()``` OR ```$('.selected-flag').trigger('click')``` OR ```$('.selected-flag').trigger('click.intlTelInput1') ``` it show dropdown and hide it in one moment.
Because this handler trigger two times.
```
$("html").on("click" + this.ns, function(e) {
      if (!isOpening) {
        that._closeDropdown();
      }
      isOpening = false;
    });
```

Can you give public method that is now private ``` _showDropdown ```

Thanks!

**Comment by jackocnr** [comment]
That's strange - it should work! If I run `$('.selected-flag').click()` on the [demo page](http://jackocnr.com/intl-tel-input.html), it works fine. Does it work for you on the demo page?

**Comment by nicksyndicate** [comment]
From ```console``` it will be fine

And if i do handler, this event is bubling. And after open it, it close. in one moment.
```
$('.open').on('click', function {
$('.selected-flag').click()
})
```

one variant is to do somth like ``` event.stopPropogation()``` but this is wrong case.
Another one public method

**Comment by jackocnr** [comment]
Oh I see, because you're only triggering this inside another click event handler, so you trigger the open, but then the original real click event bubbles up and the plugin thinks you're trying to click-off the dropdown to close it.

Yes as you say: `event.stopPropogation()` is what you want here. http://codepen.io/jackocnr/pen/zGzMao

I don't want to open up unnecessary public methods if I don't have to.
