### ISSUE TITLE
defaultCountry auto not working in https

### ISSUE THREAD

**Issue by christianrochford** [Bluefieldscom/intl-tel-input#249]
I just transferred my site to https and the defaultCountry auto setting is not working. I've update the script to the latest version and am calling the geoIPlookup function as in the provided example but its throwing an error (if I set the ipinfo.io url as http or as https), i'm also getting the 'goog is not defined' error from the utils.js script
Thanks :)

Uncaught ReferenceError: goog is not defined(anonymous function) @ utils.js:12
jquery.min.js:4 GET https://ipinfo.io/?callback=jQuery111007281268299557269_1435658996892&_=1435658996893

**Comment by jackocnr** [comment]
Re: getIpLookup, I think ipinfo.io require you to pay to make HTTPS requests (tho I believe there are other services which offer this for free), so that's probably the problem there. Also your browser will probably throw a security error if you're on a HTTPS page, and you try to hit the plain old HTTP version of ipinfo (etc), so that's why that option isn't working either.

Re: goog is not defined error: please make sure you're including build/utils.js and not src/utils.js.

**Comment by adrianmann** [comment]
What are the other services?

**Comment by jackocnr** [comment]
Other ones I have heard of are: [freegeoip](https://freegeoip.net/) and [telize](https://telize.com/) (who's website says they support HTTPS), but I'm sure there are more...

**Comment by adrianmann** [comment]
Thanks, they are places to start at least.

**Comment by JamieMcDonnell** [comment]
I too am getting:
Uncaught ReferenceError: goog is not defined

on the following:
goog.require('i18n.phonenumbers.PhoneNumberFormat');

This is only when I include:
utilsScript: "js/utils.js"

"js/utils.js" has been copied from 'bower_components/intl-tel-input/build/js' in my Gruntfile when I compile.

Anyone any ideas how to get around this so I can get formatting back?

Thanks

Jamie
