### ISSUE TITLE
geoIpLookup fails on immediate callback

### ISSUE THREAD

**Issue by durkes** [Bluefieldscom/intl-tel-input#252]
I am testing the latest version 6.0.4 and found that geoIpLookup fails if the callback is fired immediately. I have worked around the issue by using setTimeout. Examples below:

Does not work:
```
nationalMode: false,
defaultCountry: 'auto',
preferredCountries: [ 'us', 'ca', 'gb'],
utilsScript: 'intlTelInput/js/utils.js',
geoIpLookup: function (callback) {
	callback('ca');
}
```

Workaround that works:
```
nationalMode: false,
defaultCountry: 'auto',
preferredCountries: [ 'us', 'ca', 'gb'],
utilsScript: 'intlTelInput/js/utils.js',
geoIpLookup: function (callback) {
	setTimeout(function () {
		callback('ca');
	});
}
```

When geoIpLookup fails with the immediate callback, the flag is unselected and the input errors on focus with: Cannot read property 'dialCode' of undefined

Thank you for a useful and thorough plugin - I hope this is helpful.

**Comment by jackocnr** [comment]
Confirmed. This is probably because the plugin has not finished initialising when it tries to call it's own public `autoCountryLoaded` method. I don't have access to a dev computer right now, but could you possible test a potential solution for me? Try adding your setTimeout wrapper to this line in the `_loadAutoCountry` function:

```js
$(".intl-tel-input input").intlTelInput("autoCountryLoaded");
```

If that fixes the problem, it would be great if you could do a pull request. Cheers!

**Comment by durkes** [comment]
Ok - you knew right where to go - this fixed it. Thank you!
See https://github.com/Bluefieldscom/intl-tel-input/pull/253
