### ISSUE TITLE
Support for Antarctica?

### ISSUE THREAD

**Issue by mpmurph** [Bluefieldscom/intl-tel-input#275]
Hi! I am trying to integrate an address form with collecting a user's phone number using intl-tel-input. 

I was randomly testing addresses and ran one for Antarctica which in turn populated intl-tel-input's defaultCountry with continent code "aq" and, when I got an error back, realized that intl-tel-input doesn't include Antarctica's dialing code of +672. 

I know this represents a tiny portion of users but was wondering if there are plans to include it? If the issue is establishing what to use for a flag, perhaps the emblem of the Antarctic Treaty (as officially resolved in 2002: http://www.ats.aq/devAS/info_measures_listitem.aspx?lang=e&id=289) could be used in lieu of a flag?

A minor point in an otherwise excellent package! Thank you!

**Comment by mpmurph** [comment]
Just realized that +672 is also the dialing code for Norfolk Island and when I enter "nf" in lieu of "aq," the national number format for Norfolk Island seems to correspond with Antarctica's too (although I can't find any definite Antarctic numbers to be absolutely sure). In light of that, I will do a little behind the scenes country code switcheroo if a user enters an address in the Antarctic.

**Comment by jackocnr** [comment]
According to Wikipedia's [List of country calling codes](https://en.wikipedia.org/wiki/List_of_country_calling_codes), +672 is the dial code of Australian External Territories, which include Norfolk Island (+672 3) and Australian Antarctic Territory (+672 1). I think we should update the metadata to reflect that, seeing as Australian Antarctic Territory just uses Australia's normal flag, so that's easy.

Unfortunately I don't have time to implement this myself right now, but I would be happy to accept a pull request.

**Comment by jackocnr** [comment]
See comment on pull request.
