### ISSUE TITLE
Auto placeholder creates slightly-confusing UX

### ISSUE THREAD

**Issue by onassar** [Bluefieldscom/intl-tel-input#305]
Thanks for everything you've done with this library.
I'm sure it'll save be dozens of hours.

Slight issue:
The auto placeholder provides the following (for example):
![](https://i.imgur.com/qfEftl7.png)

So as an end-user, the first thing I think is "Oh, I guess I put in my area code, and constrain them with braces". Braces being `(` and `)`

However the input doesn't allow me to do so.
Is there an option to allow `(`, `)` and `-` characters so that the placeholder makes a bit more sense?

**Comment by jackocnr** [comment]
Yer this is a good point. Unfortunately we cannot just allow the user to enter those chars because all of our formatting is automatically done using libphonenumber and they say that north american numbers with <8 digits should be formatted as "555-5555", so when you start typing a north american number, it auto formats it like that - with no leading `(`.

Normally if the user tries to enter a non-numeric char when the next char in the number should be a formatting char, then it will automatically add that formatting char for them. But in this case, libphonenumber thinks the next char is not a formatting char, it is a digit. If we could find a way to tell libphonenumber to disable this short (7 digit) formatting, and always just assume that north american numbers will be the full (10 digit) length, then it would work. There may well be a way to do this, but I don't have time to look into it. That said, I welcome pull requests!

**Comment by onassar** [comment]
Gotcha makes sense. Is it possible to change the placeholder for north american numbers, such that it shows it at 555-555-5555?
That might get around the slight UX confusion

**Comment by jackocnr** [comment]
Well we also use libphonenumber to generate example numbers for each country, so again the issue is with them.

FYI as a hacky workaround, you can hardcode the placeholder yourself to whatever you want by setting the placeholder attribute on the input element in the HTML, but then it will always be that - it wont update for each country.

As for a real solution, I think that the current placeholder value is the standard way to format north american numbers, so that's not the problem. I think the solution to this is to figure out how to get the AsYouTypeFormatter to always format to the full 10 digit number - if there isn't already an option to do this, then you could open an issue with them on the [libphonenumber github](https://github.com/googlei18n/libphonenumber).

**Comment by onassar** [comment]
Okay thanks for looking at this @jackocnr. I'll likely use a Geo to see if they're in the US, and if that's the case, switch the placeholder. That should get me to where I want to be (for now..)

All the best!
