### ISSUE TITLE
Switzerland validation number

### ISSUE THREAD

**Issue by st4rg33k** [Bluefieldscom/intl-tel-input#307]
Hi !

The international prefix for switzerland is 0041 or +41.
But, the plugin return **no error** when the number from 0031 or +31 to 0091 or +91, this number: +9801707064545 and more.

For switzerland number:
Prefix: 0041 or +41 26 745 21 21
Number: 026 746 21 21

I would like to use your plugin to put it into production website, but it is currently not possible with this issue.
Many thanks !

**Comment by jackocnr** [comment]
The validation just checks that the number is valid - it doesn't check that it belongs to any specific country. If you want to do that, the best thing to do is to check that the currently selected country is Switzerland - see `getSelectedCountryData`.

**Comment by st4rg33k** [comment]
Thanks for your answer.
00 31 79 701 2782 return with ```getSelectedCountryData``` "ch" in the iso2 format -> It is false.
but with number +31 79 701 2782 it return undefined -> It is correct.

Presently, I have configured like this:
```
var telInput = jQuery("#mobile-number");
                telInput.intlTelInput({
                    defaultCountry: "CH",
                    onlyCountries: ["ch"],
                });
```
Because-that people must enter a Swiss number.

00 31 79 701 2782 return **ch** (iso2) with ```getSelectedCountryData``` function. But it is not a Swiss number.

**Comment by jackocnr** [comment]
We don't accept "00" as the international call prefix because it is not a standard, and it doesn't work in other countries. e.g. to call +31 79 701 2782 from the USA, you would have to dial 011 31 79 701 2782. We only update the country when you type a "+", so if you just type a number starting with "00" it will just stay on the currently selected country (e.g. Switzerland in this case).
