### ISSUE TITLE
Curacao country code is incorrect

### ISSUE THREAD

**Issue by deviarte** [Bluefieldscom/intl-tel-input#311]
Currently you have the Curacao country code set as +599 which is not correct. The correct country code is +5999 (three nines). The current version displays a placeholder that includes the 9 in the phone number. But residents of Curacao never dial with the 9 in front. They just dial: 555-5555 not 9-555-5555.

While officially it might be: +599, but practically it's +5999

https://en.wikipedia.org/wiki/Cura%C3%A7ao

Note: i live in Curacao.

**Comment by jackocnr** [comment]
So I think there are two problems: firstly, the placeholder, and secondly that `isValidNumber` returns false for "555 5555" (when Curacao is selected). We use [libphonenumber](https://github.com/googlei18n/libphonenumber) for both of these functions - we use it to get an example number for the country for the placeholder, and we use their number validation functionality as well. You can see a [demo of libphonenumber here](https://rawgit.com/googlei18n/libphonenumber/master/javascript/i18n/phonenumbers/demo-compiled.html) - try entering 5555555 and type cw as the country, and submit - you will see that it says "Result from isValidNumber(): false". In order to fix these issues, you would have to raise an issue over on their Github page.
