### ISSUE TITLE
Default country before geoiplookup returns

### ISSUE THREAD

**Issue by favillar** [Bluefieldscom/intl-tel-input#324]
Hello,

I'm following the { defaultCountry: "auto"...} example.  I'm getting behavior that before the geoIpLookup function returns, the flag is just a gray rounded rectangle (likely not set; the function eventually returns after a few seconds and a flag is set).  Is there a way to set a default country while the request is processing?

Thanks!

**Comment by jackocnr** [comment]
No, there is currently no way to do that, and I think it would be a bad experience if we showed a random flag for a few seconds, and then it suddenly changed to your country's flag.

**Comment by favillar** [comment]
<img width="224" alt="noflag" src="https://cloud.githubusercontent.com/assets/13543086/11286357/6ee8a0a0-8ec9-11e5-9726-b8e2c28666a3.png">

So the reason I ask is not because it's simply a "bad experience", but because our users are getting errors in this state.  We have a button we dynamically enable based on validation, and if there is no flag shown, we are getting a "Cannot read property 'iso2' of undefined" if the user tries to type in the input box.  If there would be a fix for this, that would be awesome.

**Comment by jackocnr** [comment]
So I think your problem is that you're calling isValidNumber before the plugin has finished initializing? You can tell when the plugin has finished initializing using the `done` callback. Maybe if this is taking a while, you could display a spinner or something? Maybe disable the input so the user cannot modify it until it's finished initializing?

What do you think would be the best user experience? I really don't like the idea of showing some random (wrong) flag while the plugin is initializing, and then suddenly changing it when it's ready. But I'm open to other ideas. Personally, I think the best/simplest solution is to prevent the user interacting with the input while the plugin is still initializing. How you communicate this information is up to you, and you can use the `done` callback to know when it's ready.
