### ISSUE TITLE
Publish to npm

### ISSUE THREAD

**Issue by lloydwatkin** [Bluefieldscom/intl-tel-input#54]
I'm using `browserify` for my project, so it would be great to see this on npm

**Comment by ConAntonakos** [comment]
What's the best way to expose the npm module? I'm simply requiring it and trying to expose it within the compilation process via webpack, but I'm getting an empty object. Any ideas?

**Comment by lorensr** [comment]
@jackocnr I have a similar problem – after switching from Bower to npm, I've tried including `'intl-tel-input'` and `'intl-tel-input/build/js/intlTelInput.js'`, but with both I get the error `TypeError: $(...).intlTelInput is not a function`. Should just including get your module to add itself to jquery, or is there something I need to do? Perhaps it's not being loaded because there's no `main` in your `package.json`? 

A couple other examples are [sweetalert](https://github.com/t4t5/sweetalert/blob/master/package.json), which after including, a global is available, and [node-waves](https://github.com/fians/Waves/blob/master/package.json), which I have to assign to a variable myself.

**Comment by jackocnr** [comment]
So I haven't done this for a while, but I can tell you how we were doing it in the last project I was working on a few months ago: we used npm to install intl-tel-input (instead of bower), and we used browserify to build our JS app, and the way we did it was to have a global jquery, and then in the view that wanted to use this plugin, I just did `require("intl-tel-input");` at the top (I didn't assign it to a variable), and then to use it I just did `this.ui.phone.intlTelInput();` - this is a Marionette.js ItemView, so this.ui.phone is the jQuery object for the input.

**Comment by pjebs** [comment]
Is the above instructions still valid?

I have jquery in global namespace.
I am using browserify.
I have done  `npm install intl-tel-input --save`
I have added `require("intl-tel-input");` at the top of file.

I tried to use: `$(this.refs.input).intlTelInput();`, where `this.refs.input` refers to actual input box in DOM.

**The error I get is: `TypeError: $(...).intlTelInput is not a function`**

**Comment by pjebs** [comment]
I tried it with `$(this.refs.input).intlTelInput();` too. Same result.

**Comment by jackocnr** [comment]
Nothing has changed so that really should still work. Unfortunately I personally no longer work with Browserify so I can't confirm that, but maybe someone else can?

**Comment by pjebs** [comment]
I gave up. Just using the html script tag.

**Comment by andreiho** [comment]
Using a shim fixed it for me:

```
"browser": {
  "jquery": "./node_modules/jquery/dist/jquery.js"
},
"browserify": {
  "transform": ["browserify-shim"]
},
"browserify-shim": {
  "jquery": "$",
  "intl-tel-input": {
    "depends": ["jquery"]
  }
}
```

**Comment by jevgenigavrilov** [comment]
using Browserify and this works for me `intlTelInput = require('intl-tel-input');`
